variable "db_subnet_list" {}
variable "wordpress_rds_sg" {}
variable "rds_db_name" {}
variable "rds_db_user" {}
variable "rds_db_password" {}
variable "rds_db_engine" {}
variable "rds_db_engine_version" {}
variable "rds_instance_class" {}
variable "multi_az" {}
variable "availability_zone" {}
variable "rds_storage_type" {}
variable "rds_allocated_storage" {}